name: Lint
on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  validate-hacs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - uses: actions/setup-node@v4 # Download baseline yarn
      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version-file: package.json
          cache: yarn

      - run: yarn install
      - run: yarn lint:check
      - run: yarn build
